### ISSUE TITLE
Debug Assertion Failed!

### ISSUE THREAD

**Issue by drzymalski** [DoodAbooD/AES#1]
Hello,
I cannot decrypt files using your program.
Problem is with the line
> while (*uitr != '*') uitr--;

I have error "Debug Assertion Failed" with message: "cannot dereference string iterator because it is out of range".

**Comment by DoodAbooD** [comment]
Hey there,
I'm guessing you meant line 1093:
`	while (*uitr != '*') uitr--;
`
At this block, the code is checking for a flag that should exist in the file if it was encrypted using the same program, my guess is that you are trying to decrypt a file that was encrypted elsewhere? let me know if that is not the case.. but if it is then I'm afraid this program only allows you to decrypt files that were originally encrypted with it. 
To further explain whats causing that error, the iterator checks for the '*' character placed by the encryption code to indicate the start of the flag,  but it seems to not be finding it, causing the iterator to go out of range and fail with that error when dereferenced. I should probably edit the code to make it stop looking when it reaches the beginning of file, so thank you for pointing it out.
